### ISSUE TITLE
Optimization of projects & stars on mobile 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-galaxy#11]
On mobile these are really kinda huge, optimization proposal in #10 could already help, but maybe it should resize even slightly more on mobile?

![screenshot_20181204-184915_chrome](https://user-images.githubusercontent.com/6533925/49462112-8f6af600-f7f5-11e8-9506-1a98c63f085d.jpg)
![screenshot_20181204-184813_chrome](https://user-images.githubusercontent.com/6533925/49462113-8f6af600-f7f5-11e8-8ccd-d70bd6f288a6.jpg)

**Comment by geleeroyale** [comment]
set to same settings as desktop 100px height

**Comment by krrisis** [comment]
Wooooow soo much better, thx
