### ISSUE TITLE
empty space in frame

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-galaxy#13]
tiny thing but still ;-) this block is missing some grey or just should be 'tighter' around the image, shows up on desktop & moble 

![image](https://user-images.githubusercontent.com/6533925/49463589-208f9c00-f7f9-11e8-80dc-a639e0e9d4c5.png)

**Comment by geleeroyale** [comment]
uploaded the same screenshot but without the black bar to contentful

**Comment by krrisis** [comment]
still there? didn't it save? 

![image](https://user-images.githubusercontent.com/6533925/49986202-3a567f00-ff6f-11e8-8e43-07fa13b255c2.png)

**Comment by geleeroyale** [comment]
takes a full reload because I changed the screenshot in contentful to the same without black bar
