### ISSUE TITLE
Update the join page with extra block of text + optimize mobile view

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-galaxy#15]
as described in briefing doc https://docs.google.com/document/d/1LmAq2q0NuH5-W_z3itYljqvTd6RacXSLCFC36viRI4k/edit?usp=sharing

**Comment by krrisis** [comment]
Thx for the changes @geleeroyale !!! Looks great, also on mobile. Could you only still fix this: 
'Slack title should be the same size as Riot (even if faded out a bit)'

**Comment by geleeroyale** [comment]
fixed in contentful
