### ISSUE TITLE
minor mobile improvements 

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-galaxy#19]
1) this title is not too readable: 

![image](https://user-images.githubusercontent.com/6533925/49984958-7a673300-ff6a-11e8-88ec-3f31d0f6359c.png)

2) this looks not ideal.. I know it's bcs you split it in two blocks on contentful but that also breaks it on the desktop version in an unnatural way. Is it possible to put both texts in one text block? 

![image](https://user-images.githubusercontent.com/6533925/49985263-aa630600-ff6b-11e8-9e63-e30aea449750.png)

**Comment by geleeroyale** [comment]
@2: Can't we change the text to be constructed out of two paragraphs? Would be more readable than putting everything in a large text block.

Edit: Made it so, by putting the rest of the sentence in section 1.
