### ISSUE TITLE
optimize header spacing on desktop

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-galaxy#20]
Great that you moved it up but now it's moved up too much. :) On mobile it looks good, on desktop it's now a bit cluttered: 

![image](https://user-images.githubusercontent.com/6533925/49985424-2eb58900-ff6c-11e8-9013-b9718f4398c6.png)

**Comment by geleeroyale** [comment]
hmmm - can't reproduce this except when I put in an extreme aspect ratio

[Edit: Making some changes now that will be live with next commit - please check if solved]

**Comment by krrisis** [comment]
yes, seems solved on all my screens now, thx!
