### ISSUE TITLE
We need more logos on the bottom of our website!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-galaxy#22]
We have sooooooooo many friends! I got logos from MakerDAO and Alibre... but i bet we have more! 

graceaid?
who else!?

https://github.com/Giveth/Communication/issues/147

**Comment by geleeroyale** [comment]
Yes - keep them coming - we can add as many as we like :)

**Comment by geleeroyale** [comment]
Add blockchain4humanity

**Comment by geleeroyale** [comment]
added requested friends
